export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_MAINCOURT_DATA = 'SET_MAINCOURT_DATA';
export const SET_ALL_MAINCOURT_DATA = 'SET_ALL_MAINCOURT_DATA';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SET_SKILL_LEVEL = 'SET_SKILL_LEVEL';
export const SET_COUPONS = 'SET_COUPONS';
export const PACKAGES_LIST = 'PACKAGES_LIST';
